/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DynamicSection: typeof import('./components/DynamicSection.vue')['default']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    GlobalLoading: typeof import('./components/GlobalLoading.vue')['default']
    MarkdownEditor: typeof import('./components/MarkdownEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
